### PR TITLE
GCD using Eucledian Algorithm.

### PR DESCRIPTION
**Pull request by SivaKumar2001**

### CODE REVIEW

**Comment by shoaibrayeen** [comment]
- post your solutions at correct place
- there are GCD folder in Basic one.
- push your codes there

**Comment by shoaibrayeen** [comment]
- push code here for GCD - https://github.com/shoaibrayeen/Programmers-Community/tree/master/Basic/Find%20GCD%20of%20Two%20Numbers
- change filename as SolutionBySivaKumar.cpp

**Comment by shoaibrayeen** [comment]
- You have added LCM codes in GCD folder.
- add GCD code in GCD folder and LCM code in LCM Folder

**Comment by SivaKumar2001** [comment]
> * You have added LCM codes in GCD folder.
> * add GCD code in GCD folder and LCM code in LCM Folder

Hey Shoaibrayeen, I have update my code please verify it and thanks for accepting my pull request.

**Pull request closed without merging**
