### PR TITLE
Added setbit_Count

### PR DESCRIPTION
**Pull request by M0hitSingh**

### CODE REVIEW

**Comment by M0hitSingh** [comment]
Hey, can you  merge this PR , and label it as hacktober

**Comment by shoaibrayeen** [comment]
@M0hitSingh Please take user input

**Comment by shoaibrayeen** [comment]
can't merge until it meets the guideline

**Comment by M0hitSingh** [comment]
@shoaibrayeen please check if any other change needed

**Comment by M0hitSingh** [comment]
@shoaibrayeen  please look, and merge

**Review by shoaibrayeen — APPROVED** [review]

**Pull request merged**
