### PR TITLE
Merge sort in cpp

### PR DESCRIPTION
**Pull request by navdiya-nikunj**
I saw that there is no merge sort in data structure/array So I wanted to add
- Contains merge sort program in cpp
- it has comments for beginner to understand

### CODE REVIEW

**Comment by shoaibrayeen** [comment]
@navdiya-nikunj remove extra files from PR

**Comment by navdiya-nikunj** [comment]
Okay 👌

**Comment by navdiya-nikunj** [comment]
Done @shoaibrayeen

**Comment by navdiya-nikunj** [comment]
updated it.

**Review by shoaibrayeen — APPROVED** [review]

**Comment by shoaibrayeen** [comment]
@navdiya-nikunj Please check my commit, next time you raise a PR, please create file name like that

**Comment by navdiya-nikunj** [comment]
Ok thank you

**Pull request merged**
