### PR TITLE
added few programns

### PR DESCRIPTION
**Pull request by pratham27037**

### CODE REVIEW

**Review by shoaibrayeen — CHANGES_REQUESTED** [review]
- Change filename as SolutionByYourName.cpp
And then comment

**Comment by pratham27037** [comment]
updated the file

**Review by shoaibrayeen — CHANGES_REQUESTED** [review]
- You need to reverse a string, not a number.
- Kindly change and comment.

**Comment by pratham27037** [comment]
updated the string palindrome program

**Review by shoaibrayeen — APPROVED** [review]

**Pull request merged**
