### PR TITLE
C Language 

### PR DESCRIPTION
**Pull request by yashpatel08**
I have upload  programs in c language . it will cover consepts of c language , if it is helpfull then tell me ASAP.
@shoaibrayeen 
i have made all changes please check and tell if it is correct ASAP .

### CODE REVIEW

**Comment by shoaibrayeen** [comment]
Hi @yashpatel08 
Create all files in the below format
- C/Program Name/SolutionByYash.c
for example, Addition of two numbers file should be
- C/Addition of Two Numbers/SolutionbyYash.c, do push all the files like this.

**Comment by yashpatel08** [comment]
I have make all changes as you have suggested please check and tell me if
it is ok or not ASAP.

**Review by Assia-el — COMMENTED** [review]
That really help mw

**Comment by shoaibrayeen** [comment]
Still not following the guidelines, also Please make one PR / file

**Pull request closed without merging**
