### PR TITLE
Binary Tree with Templates

### PR DESCRIPTION
**Pull request by nikunj3011**
Binary-Tree which supports all data types

### CODE REVIEW

**Review by shoaibrayeen — CHANGES_REQUESTED** [review]
- Kindly add only solution file as solutionByNikunj.cpp and remove all the files.

**Comment by nikunj3011** [comment]
done

**Comment by nikunj3011** [comment]
is it good or not?

**Review by shoaibrayeen — CHANGES_REQUESTED** [review]
Use input from user
and add only readMe and Solution file

**Comment by nikunj3011** [comment]
done anything else?

**Review by nikunj3011 — COMMENTED** [review]
done

**Review by shoaibrayeen — APPROVED** [review]

**Pull request merged**
